### ISSUE TITLE
Using showDialog or showModalBottomSheet on landscape rotates the orientation

### ISSUE THREAD

**Issue by FRodriguez18** [sergiyvergun/orientation_helper#2]
If the current route is in landscape and I try to use either `showDialog` or `showModalBottomSheet`, the screen will rotate and stay in portrait until I hit the back button.

The route is defined as
```
...
RouteDetails(
  name: '/screen',
  page: Screen(),
  orientation: ScreenOrientation.landscapeOnly,
),
...
```

**Comment by sergiyvergun** [comment]
Thank you for your feedback! Check out 1.0.2, it's fixed now.
